version: "2"
services:
  zappy:
    container_name: zappy
    environment: 
      env_file: .env
      NODE_ENV: staging
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"